config/routes.rb
BibFoaf::Application.routes.draw do
  root 'authors#index'
  resources :authors, only: [:index, :show]
  resources :status, only: [:index]

end

app/models/author.rb
class Author < Neography::Node
  extend Helpers::ParseHelper

  def self.fulltext_index_name
    'authors_fulltext_index'
  end

  def self.url
    puts self.inspect
    self["self"]
  end

  def self.find(author_name)
    Neography::Node.find('authors_index', :name, transform_to_index(author_name))
  end

  def self.create(properties)
    Neography::Node.create({type: :author}.merge(properties))
  end

  def self.find_or_create(name)
    author = find(name)
    unless author
      author = create(name: name)
      author.add_to_index('authors_index', :name, transform_to_index(name))
      author.add_to_index('types_index', :type, :author)
    end
    author
  end

  def self.add_fulltext_index(author)
    author.add_to_index(fulltext_index_name, :name, transform_to_index(author[:name]))
  end

  def self.fulltext_find(term)
    term = transform_to_index(term)
    author = find(term)
    return author if author
    return [] if term.size < 3
    term = term.gsub(" ","")
    authors = Neography::Node.find(fulltext_index_name, "name:*#{term}*")
    authors
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_filter :save_query, only: :index

  def index
    if params[:name]
      discovering_service = Discovering::Service.new
      @authors = Author.fulltext_find(params[:name])
      if @authors.nil?
        @authors = []
      elsif @authors.is_a? Array
        @author = nil
        @author_groups = []
        @foaf_authors = []
      else
        @author = @authors
        @authors = [@author]
        @author_groups = discovering_service.discover_group_authors(@author)
        @foaf_authors = discovering_service.foaf_authors(@author)
      end
    end
  end

  def show
    discovering_service = Discovering::Service.new
    @author = Neography::Node.load(params[:id])
    @author_groups = discovering_service.discover_group_authors(@author)
    @foaf_authors = discovering_service.foaf_authors(@author)
    render 'index'
  end

  private

  def save_query
    session[:queries] = "" unless session.has_key?(:queries)
    if params[:name]
      session[:queries] += params[:name] + '|' if session[:queries].split('|').all? { |s| s != params[:name] }
    end
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper

  def neo4j_node_url(neo4j_id)
    "http://localhost:7474/db/data/node/#{neo4j_id}"
  end

end

app/views/authors/index.html.haml
%h1
  Find authors

= form_tag authors_path, method: :get do
  = text_field_tag 'name', params[:name]
  = submit_tag 'Find'

  - if session[:queries]
    %strong= 'Last queries: '
    - session[:queries].split('|').each do |param|
      = link_to param, authors_path(name: param)
- if params[:name]
  - if @authors.size == 0
    %hr
    = "Author with '#{params[:name]}' not found in dataset"
  - elsif @authors.size > 1
    %hr
    %h2= "Query: '#{params[:name]}'"
    - @authors.each do |author|
      = link_to author[:name], author_path(author.neo_id)
      %br

%hr

- if @author
  %h1= @author[:name]
  %h2= "FOAF Authors (#{@foaf_authors.count})"
  = @foaf_authors.map{|author_name,count| "#{author_name} (#{count / 4})" }.join(', ')

  %hr
  - @author_groups.each_with_index do |group_author, index|
    %h1= "#{@author[:name]} num. #{index+1}"

    - unless group_author[:articles].empty?
      %h2= 'Articles'
      - group_author[:articles].each do |article|
        = article.outgoing(:year).first[:year]
        %strong= article[:title]
        %i
          = '('
          = article.outgoing(:authors).map{|author| link_to author[:name], author_path(author.neo_id)}.join(', ').html_safe
          = ')'
        %br

    - unless group_author[:in_proceedings].empty?
      %h2= 'In Proceedings'
      - group_author[:in_proceedings].each do |in_proceeding|
        = in_proceeding.outgoing(:year).first[:year]
        %strong= in_proceeding[:title]
        %i
          = '('
          = in_proceeding.outgoing(:authors).map{ |author| link_to author[:name], author_path(author.neo_id) }.join(', ').html_safe
          = ')'
        %br

    - unless group_author[:in_collections].empty?
      %h2= 'In Collections'
      - group_author[:in_collections].each do |in_collection|
        = in_collection.outgoing(:year).first[:year]
        %strong= in_collection[:title]
        %i
          = '('
          = in_collection.outgoing(:authors).map{ |author| link_to author[:name], author_path(author.neo_id) }.join(', ').html_safe
          = ')'
        %br

    %hr